### ISSUE TITLE
Element hidden when starts on view port

### ISSUE THREAD

**Issue by aotaduy** [caioiglesias/scroll-animate-directive#2]
The element is hidden by default when applied the ani-view directive and is already inside the viewport, could we show it if it is already there? Maybe executing once the scroll event handler at page load?

**Comment by caioiglesias** [comment]
I'll take a look at your commit soon!
Please just remove that extra file with the "~" (tilde) suffix I commented on.

Thanks @guitassinari!

**Comment by guitassinari** [comment]
Already removed it.

You're welcome @caioiglesias
